export const FETCH_ALL_ARTICLE = "FETCH_ALL_ARTICLE"
export const FETCH_ALL_ARTICLE_SUCCESS = "FETCH_ALL_ARTICLE_SUCCESS"
export const FETCH_ALL_ARTICLE_ERROR = "FETCH_ALL_ARTICLE_ERROR"

export const FETCH_ARTICLE_WITH_ID = "FETCH_ARTICLE_WITH_ID"
export const FETCH_ARTICLE_WITH_ID_SUCCESS = "FETCH_ARTICLE_WITH_ID_SUCCESS"
export const FETCH_ARTICLE_WITH_ID_ERROR = "FETCH_ARTICLE_WITH_ID_ERROR"

export const UPDATE_ARTICLE = "UPDATE_ARTICLE"
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS"
export const UPDATE_ARTICLE_ERROR = "UPDATE_ARTICLE_ERROR"

export const ADD_ARTICLE = "ADD_ARTICLE"
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS"
export const ADD_ARTICLE_ERROR = "ADD_ARTICLE_ERROR"

export const FETCH_ALL_CATEGORY = "FETCH_ALL_CATEGORY"
export const FETCH_ALL_CATEGORY_SUCCESS = "FETCH_ALL_CATEGORY_SUCCESS"
export const FETCH_ALL_CATEGORY_ERROR = "FETCH_ALL_CATEGORY_ERROR"

export const FETCH_CATEGORY_WITH_ID = "FETCH_CATEGORY_WITH_ID"
export const FETCH_CATEGORY_WITH_ID_SUCCESS = "FETCH_CATEGORY_WITH_ID_SUCCESS"
export const FETCH_CATEGORY_WITH_ID_ERROR = "FETCH_CATEGORY_WITH_ID_ERROR"

export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR"

export const ADD_CATEGORY = "ADD_CATEGORY"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR"

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION"
export const HIDE_NOTIICATION = "HIDE_NOTIICATION"

export const FETCH_ALL_TYPENEWS = "FETCH_ALL_TYPENEWS"
export const FETCH_ALL_TYPENEWS_SUCCESS = "FETCH_ALL_TYPENEWS_SUCCESS"
export const FETCH_ALL_TYPENEWS_ERROR = "FETCH_ALL_TYPENEWS_ERROR"

export const FETCH_TYPENEWS_WITH_ID = "FETCH_TYPENEWS_WITH_ID"
export const FETCH_TYPENEWS_WITH_ID_SUCCESS = "FETCH_TYPENEWS_WITH_ID_SUCCESS"
export const FETCH_TYPENEWS_WITH_ID_ERROR = "FETCH_TYPENEWS_WITH_ID_ERROR"

export const FETCH_TYPENEWS_WITH_CATEGORY_ID = "FETCH_TYPENEWS_WITH_CATEGORY_ID"
export const FETCH_TYPENEWS_WITH_CATEGORY_ID_SUCCESS = "FETCH_TYPENEWS_WITH_CATEGORY_ID_SUCCESS"
export const FETCH_TYPENEWS_WITH_CATEGORY_ID_ERROR = "FETCH_TYPENEWS_WITH_CATEGORY_ID_ERROR"

export const UPDATE_TYPENEWS = "UPDATE_TYPENEWS"
export const UPDATE_TYPENEWS_SUCCESS = "UPDATE_TYPENEWS_SUCCESS"
export const UPDATE_TYPENEWS_ERROR = "UPDATE_TYPENEWS_ERROR"

export const ADD_TYPENEWS = "ADD_TYPENEWS"
export const ADD_TYPENEWS_SUCCESS = "ADD_TYPENEWS_SUCCESS"
export const ADD_TYPENEWS_ERROR = "ADD_TYPENEWS_ERROR"


export const FETCH_QUESTION_TYPE = "FETCH_QUESTION_TYPE"
export const FETCH_QUESTION_TYPE_SUCCESS = "FETCH_QUESTION_TYPE_SUCCESS"
export const FETCH_QUESTION_TYPE_ERROR = "FETCH_QUESTION_TYPE_ERROR"


export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const FETCH_TEST_TYPE = "FETCH_TEST_TYPE"
export const FETCH_TEST_TYPE_SUCCESS = "FETCH_TEST_TYPE_SUCCESS"
export const FETCH_TEST_TYPE_ERROR = "FETCH_TEST_TYPE_ERROR"

// export const FETCH_TEST_TYPE = "FETCH_TEST_TYPE"
// export const FETCH_TEST_TYPE_SUCCESS = "FETCH_TEST_TYPE_SUCCESS"
// export const FETCH_TEST_TYPE_ERROR = "FETCH_TEST_TYPE_ERROR"

export const FETCH_GROUP_ANSWERS = "FETCH_GROUP_ANSWERS"
export const FETCH_GROUP_ANSWERS_SUCCESS = "FETCH_GROUP_ANSWERS_SUCCESS"
export const FETCH_GROUP_ANSWERS_ERROR = "FETCH_GROUP_ANSWERS_ERROR"

export const FETCH_GROUP_ANSWERS_WITH_ID = "FETCH_GROUP_ANSWERS_WITH_ID"
export const FETCH_GROUP_ANSWERS_WITH_ID_SUCCESS = "FETCH_GROUP_ANSWERS_WITH_ID_SUCCESS"
export const FETCH_GROUP_ANSWERS_WITH_ID_ERROR = "FETCH_GROUP_ANSWERS_WITH_ID_ERROR"

export const ADD_GROUP_ANSWERS = "ADD_GROUP_ANSWERS"
export const ADD_GROUP_ANSWERS_SUCCESS = "ADD_GROUP_ANSWERS_SUCCESS"
export const ADD_GROUP_ANSWERS_ERROR = "ADD_GROUP_ANSWERS_ERROR"


export const UPDATE_GROUP_ANSWERS = "UPDATE_GROUP_ANSWERS"
export const UPDATE_GROUP_ANSWERS_SUCCESS = "UPDATE_GROUP_ANSWERS_SUCCESS"
export const UPDATE_GROUP_ANSWERS_ERROR = "UPDATE_GROUP_ANSWERS_ERROR"


export const FETCH_QUESTION = "FETCH_QUESTION"
export const FETCH_QUESTION_SUCCESS = "FETCH_QUESTION_SUCCESS"
export const FETCH_QUESTION_ERROR = "FETCH_QUESTION_ERROR"

export const FETCH_QUESTION_WITH_ID = "FETCH_QUESTION_WITH_ID"
export const FETCH_QUESTION_WITH_ID_SUCCESS = "FETCH_QUESTION_WITH_ID_SUCCESS"
export const FETCH_QUESTION_WITH_ID_ERROR = "FETCH_QUESTION_WITH_ID_ERROR"

export const ADD_QUESTION = "ADD_QUESTION"
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS"
export const ADD_QUESTION_ERROR = "ADD_QUESTION_ERROR"

export const EDIT_QUESTION = "EDIT_QUESTION"
export const EDIT_QUESTION_SUCCESS = "EDIT_QUESTION_SUCCESS"
export const EDIT_QUESTION_ERROR = "EDIT_QUESTION_ERROR"


export const DELETE_QUESTION = "DELETE_QUESTION"
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS"
export const DELETE_QUESTION_ERROR = "DELETE_QUESTION_ERROR"

export const FETCH_GROUP_ANSWERS_WITH_ID_TEST_TYPE = "FETCH_GROUP_ANSWERS_WITH_ID_TEST_TYPE"
export const FETCH_GROUP_ANSWERS_WITH_ID_TEST_TYPE_SUCCESS = "FETCH_GROUP_ANSWERS_WITH_ID_TEST_TYPE_SUCCESS"
export const FETCH_GROUP_ANSWERS_WITH_ID_TEST_TYPE_ERROR = "FETCH_GROUP_ANSWERS_WITH_ID_TEST_TYPE_ERROR"