export const FETCH_ALL_ARTICLE = "FETCH_ALL_ARTICLE"
export const FETCH_ALL_ARTICLE_SUCCESS = "FETCH_ALL_ARTICLE_SUCCESS"
export const FETCH_ALL_ARTICLE_ERROR = "FETCH_ALL_ARTICLE_ERROR"

export const FETCH_ARTICLE_WITH_ID = "FETCH_ARTICLE_WITH_ID"
export const FETCH_ARTICLE_WITH_ID_SUCCESS = "FETCH_ARTICLE_WITH_ID_SUCCESS"
export const FETCH_ARTICLE_WITH_ID_ERROR = "FETCH_ARTICLE_WITH_ID_ERROR"

export const FETCH_ALL_CATEGORY = "FETCH_ALL_CATEGORY"
export const FETCH_ALL_CATEGORY_SUCCESS = "FETCH_ALL_CATEGORY_SUCCESS"
export const FETCH_ALL_CATEGORY_ERROR = "FETCH_ALL_CATEGORY_ERROR"

export const FETCH_CATEGORY_WITH_ID = "FETCH_CATEGORY_WITH_ID"
export const FETCH_CATEGORY_WITH_ID_SUCCESS = "FETCH_CATEGORY_WITH_ID_SUCCESS"
export const FETCH_CATEGORY_WITH_ID_ERROR = "FETCH_CATEGORY_WITH_ID_ERROR"

export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR"

export const ADD_CATEGORY = "ADD_ALL_CATEGORY"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR"

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION"
export const SHOW_NOTIFICATION_REQUEST = "SHOW_NOTIFICATION_REQUEST"

export const FETCH_ALL_TYPENEWS = "FETCH_ALL_TYPENEWS"
export const FETCH_ALL_TYPENEWS_SUCCESS = "FETCH_ALL_TYPENEWS_SUCCESS"
export const FETCH_ALL_TYPENEWS_ERROR = "FETCH_ALL_TYPENEWS_ERROR"

export const FETCH_TYPENEWS_WITH_ID = "FETCH_TYPENEWS_WITH_ID"
export const FETCH_TYPENEWS_WITH_ID_SUCCESS = "FETCH_TYPENEWS_WITH_ID_SUCCESS"
export const FETCH_TYPENEWS_WITH_ID_ERROR = "FETCH_TYPENEWS_WITH_ID_ERROR"

export const UPDATE_TYPENEWS = "UPDATE_TYPENEWS"
export const UPDATE_TYPENEWS_SUCCESS = "UPDATE_TYPENEWS_SUCCESS"
export const UPDATE_TYPENEWS_ERROR = "UPDATE_TYPENEWS_ERROR"

export const ADD_TYPENEWS = "ADD_TYPENEWS"
export const ADD_TYPENEWS_SUCCESS = "ADD_TYPENEWS_SUCCESS"
export const ADD_TYPENEWS_ERROR = "ADD_TYPENEWS_ERROR"


export const FETCH_QUESTION_TYPE = "FETCH_QUESTION_TYPE"
export const FETCH_QUESTION_TYPE_SUCCESS = "FETCH_QUESTION_TYPE_SUCCESS"
export const FETCH_QUESTION_TYPE_ERROR = "FETCH_QUESTION_TYPE_ERROR"
